# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 262d97f66d5c0c9a5f071a32764aa3a45a85df65420cab2e2a0a4337e9e9e09643bbdbd35f556c0b2e98c762eac17f5a70b904d24199690b997dd5a9a228855d

test:
  secret_key_base: 1ce2c9783094939c1ef1b98b65bc8bb74e32c7a17ffcb316fd83b51f41d75e6b3e82c730a024587d80a1961a1137ee0ce3227c0c78bd812fb71c5d12393d4208

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
